### ISSUE TITLE
Add scan outcome to response variables

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-trustedform#10]

**Comment by cgrayson** [comment]
As I understand the [API docs](https://support.activeprospect.com/hc/en-us/articles/201325449-Claiming-a-certificate), this means capturing the value of the array `warnings`. That's also where the "none of the provided fingerprints match" message would be.

I wonder if this should also append the `fingerprints` data?

```json
"fingerprints": {
  "matching": [],
  "non_matching": []
}
```

**Comment by cgrayson** [comment]
After more thought and a look at the response when a `scan` is requested, I think this should be higher level than just capturing `warnings`.

From a positive (required text) scan for "Free iPod": 
```json
  "warnings": [
    "string not found in snapshot"
  ],
  "scans": {
    "found": [],
    "not_found": ["Free iPod"]
  },
```

From a negative (forbidden text) scan for "Free iPod":
```json
  "warnings": [],
  "scans": {
    "found": [],
    "not_found": ["Free iPod"]
  },
```

We'll want to capture the whole `scans` object, but I think the integration should also boil the scan result down to easily rule-able booleans, e.g., `required_scan_found` and `forbidden_scan_found` (btw, I think the scan params should be renamed like that; I'll open an issue for that discussion).

**Comment by cgrayson** [comment]
After discussion with Alex, plan to make this integration set `outcome` to *failure* when the scan fails (i.e., required scan isn't found || forbidden scan is).

Will still add response variables to capture:
1. `warnings` (array)
2. `scans_found` (array)
3. `scans_not_found` (array)

Opened issue #16 to address capturing fingerprint data.

**Comment by cgrayson** [comment]
Did this wrong. TF returns _everything_ that's found in `scans.found`, whether it should have been found ("required") or should not have been ("forbidden"). So the integration will need to correlate what was sent with what came back to set this right.
