### ISSUE TITLE
Not possible to scan for multiple terms

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-trustedform#11]

**Comment by cgrayson** [comment]
One complication is that there's not support in the UI for entering an array of values. In the absence of that, the integration could treat the `scan_required_text` and `scan_forbidden_text` strings as CSVs of multiple terms, but it's less than ideal (less clear, and problematic for terms that contain commas).

Also note that the format to claim with multiple terms will be the array syntax:

`curl -X POST -H "Accept: application/json" "https://cert.trustedform.com/de1190b36526fe11c21970e712c8c869e0cbe801?email=stan@ley.com&pphone=5125558743&scan\[\]=Participation%20required&scan\[\]=privacy%20policy"`

**Comment by alexkwolfe** [comment]
Gross.

**Comment by alexkwolfe** [comment]
I think those brackets have to be URL encoded, don't they?

**Comment by alexkwolfe** [comment]
Spoiler alert: yes they have to be encoded. That's part of the reason I've avoided using that syntax in our APIs to date. The other reason is that it's gross. :bug:

http://tools.ietf.org/html/rfc1738

**Comment by alexkwolfe** [comment]
And you know I never do gross stuff. :wink:

**Comment by cgrayson** [comment]
Mentioned again today by [AP support](https://activeprospect.slack.com/archives/C034BK84K/p1498754720504150). Could be addressed via rich UI?

**Comment by mrjuicebox** [comment]
Blocker for this client's request: https://activeprospect.zendesk.com/agent/tickets/13082

**Comment by cgrayson** [comment]
Fixed as of 1.4.0.
