### ISSUE TITLE
Certificates show as masked when they are not

### ISSUE THREAD

**Issue by kcaponeAP** [activeprospect/leadconduit-integration-trustedform#26]
https://next.leadconduit.com/events/5538eba66321e59e36ace75f?event_id=5538eba76321e59e36ace763

http://screencast.com/t/IJlLMsATyp

Shows up as Masked in the event listing, when it is actually a 404:

Outcome	 error
Reason	TrustedForm error - certificate not found (404)

**Comment by cgrayson** [comment]
UI issue. Opened [client issue 695](https://github.com/activeprospect/leadconduit-client/issues/695).
