### ISSUE TITLE
Appended url is blank

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-trustedform#31]
The TrustedForm API sometimes returns an empty string for parent location. That causes the appended `url` property to be an empty string due to the [conditional logic for determining hosted_url](https://github.com/activeprospect/leadconduit-integration-trustedform/blob/b5972e7e30b9e7355a981f4b6b5bff2effe6fa4e/src/claim.coffee#L87).

**Comment by justinwinslow** [comment]
+1

**Comment by ros3bud** [comment]
Solved in 1.2.4
